
const Ports = [
    {
      title: "Movie App", 
      github: "https://github.com/ChuloCr8v/proflix", 
      demo: "https://proflix.vercel.app/", 
      img: '/../public/proflix.jpg', 
      description: "Proflix is a movie database app that can be used to get information about movies including their release date, average ratings and trailer. Movies were fetched from TheMovieDatabase.", 
      stackOne: "Html5", 
      stackTwo: "Sass", 
      stackThree: "Css3", 
      stackFour: "React-redux-toolkit", 
      featureOne: "Contains different genre of movies", 
      featureTwo: "Movie Trailers and Details about specific movies", 
      featureThree: "Responsive design across all devices", 
      featureFour: "Sleek Design"
    }, 
    {
      title: 'Grampro Photobucket', 
      img: '/../public/grampro.jpg', 
      github: "https://github.com/ChuloCr8v/grampro", 
      demo: "https://grampro.netlify.app", 
      stackOne: "Html5", 
      stackTwo: "Sass", 
      stackThree: "Css3", 
      stackFour: "Google Firebase/Firestore", 
      description: "This is a Photo Bucket that allows uploading of pictures and preview of uploaded pictures. The uploaded pictures are stored with Google Firebase which acts as the backend.", 
      featureOne: "Allows upload and preview of uploaded pictures.",
      featureTwo: "Users can only upload and preview uploads.",
      featureThree: "Mobile Responsiveness", 
      featureFour: "Spots a sleek design.", 
    }, 
    {
      title: 'Crypto Wallstreet', 
      img: '/../public/cryptowallstreet.jpg', 
      github: "https://github.com/ChuloCr8v/cryptowallstreet", 
      demo: "https://cryptowallstreet.vercel.app", 
      description: "This is a web app designed to provide current information on cryptocurrencies. With this app, you can view different cryptocurrency details, their market standings as well as their price chart. You can as well view the history of each cryptocurrency. It also contains a list of exchanges and their brief introduction. The cryptocurrency data was pulled from Coinranking API hosted on RapidAPI.", 
      stackOne: "Html5", 
      stackTwo: "Sass", 
      stackThree: "Css3", 
      stackFour: "React-redux",
      featureOne: "Displays vital information on cryptocurrencies.", 
      featureTwo: "Chart.js for displaying crypto price chart",
      featureThree: "Top cryptocurrency news update.", 
      featureFour: "Mobile Responsive.", 
    }, 
    {
      title: 'PaulRay Photography', 
      img: '/../public/paulray.jpg', 
      github: "https://github.com/ChuloCr8v/paul-ray.github.io", 
      demo: "https://paulrayphoto.netlify.app", 
      description: "This is a photography portfolio website designed to showcase the profile of a photographer. It contains details about the photographer such as skills, services, past works and contact details.", 
      stackOne: "Html5", 
      stackTwo: "Css3", 
      stackThree: "JavaScript", 
      featureOne: "Contains different sections including hero, contact, work tools and sample works.", 
      featureTwo: "Features a responsive gallery.", 
      featureThree: "Features a responsive menu", 
      featureFour: "Mobile Responsive.", 
    }, 
    { 
      title: "My First Portfolio", 
      github: "https://github.com/ChuloCr8v/chulocr8v.github.io", 
      demo: "https://chulocr8v.github.io", 
      img: '/../public/portfolio.jpg', 
      description: "This is my first portfolio website. It contains details such as my skills, work portfolio, contact and contact form.", 
      stackOne: "Html5", 
      stackTwo: "Css3", 
      stackThree: "JavaScript", 
      featureOne: "Features basic details about me.", 
      featureFour: "Mobile Responsive." 
    }, 
    {
      title: 'Shop 24Seven', 
      img: '/../public/shop.jpg', 
      github: "https://github.com/ChuloCr8v/shop24seven.github.io", 
      demo: "https://shop24seven.netlify.app/", 
      description: "This is template of an online store. It features only the landing page and no additional features.", 
      stackOne: "Html5", 
      stackTwo: "Sass", 
      stackThree: "Css3", 
      stackFour: "JavaScript",
      featureOne: "Login/Signup/Categories/Shopping Cart pages included", 
      featureTwo: "Features a responsive product gallery.", 
      featureThree: "Sleek user interface", 
      featureFour: "Mobile Responsive.", 
    }, 
    {
      title: 'Blogr Landing Page', 
      img: '/../public/blogr.jpg', 
      github: "https://github.com/ChuloCr8v/blogr-landing-page.github.io", 
      demo: "https://chulocr8v.github.io/blogr-landing-page.github.io/", 
      description: "This is a blogr website template design challenge which I got from front-end mentor.", 
      stackOne: "Html5", 
      stackTwo: "Css3", 
      stackThree: "JavaScript", 
      featureOne: "Built With HTML5, CSS3 and TailwindCss.",
      featureTwo: "JavaScript for basic features.", 
      featureThree: "Mobile Responsive.", 
      featureFour: "Responsive Menu"
    },
  ]
  
  export default Ports